spring.application.name=ai-news-aggregator
server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGO_URI}

groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.1-8b-instant
groq.base.url=https://api.groq.com/openai/v1/chat/completions

gemini.api.key=${GEMINI_API_KEY}
gemini.model=models/gemini-2.5-flash
gemini.base.url=https://generativelanguage.googleapis.com/v1beta

hf.api.key=${HF_API_KEY}
hf.model=facebook/bart-large-cnn
hf.base.url=https://router.huggingface.co/models

